/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'article-categories': ArticleCategory;
    'article-tags': ArticleTag;
    articles: Article;
    'article-generation-checkpoints': ArticleGenerationCheckpoint;
    'industry-landing-pages': IndustryLandingPage;
    'industry-generation-checkpoints': IndustryGenerationCheckpoint;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'article-categories': ArticleCategoriesSelect<false> | ArticleCategoriesSelect<true>;
    'article-tags': ArticleTagsSelect<false> | ArticleTagsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'article-generation-checkpoints': ArticleGenerationCheckpointsSelect<false> | ArticleGenerationCheckpointsSelect<true>;
    'industry-landing-pages': IndustryLandingPagesSelect<false> | IndustryLandingPagesSelect<true>;
    'industry-generation-checkpoints': IndustryGenerationCheckpointsSelect<false> | IndustryGenerationCheckpointsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'content-generation-settings': ContentGenerationSetting;
  };
  globalsSelect: {
    'content-generation-settings': ContentGenerationSettingsSelect<false> | ContentGenerationSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * Display category (e.g., "Social Impact", "Aerospace & Engineering")
   */
  category: string;
  filterCategory: 'nonprofit' | 'professional';
  /**
   * Uploaded project image
   */
  image?: (number | null) | Media;
  /**
   * Static path to image (e.g., /work/zero-abuse.jpg). Used if image is not uploaded.
   */
  imagePath?: string | null;
  /**
   * External website URL
   */
  link?: string | null;
  /**
   * Brief summary of the organization and what they do (2-3 sentences)
   */
  summary?: string | null;
  /**
   * Detailed article-style write-up about the organization (2-3 paragraphs)
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tags for categorization (e.g., Healthcare, Education)
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show this project prominently
   */
  featured?: boolean | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  client?: string | null;
  year?: string | null;
  /**
   * The challenge or problem we solved
   */
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Our approach and solution
   */
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?:
    | {
        metric: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
  };
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories".
 */
export interface ArticleCategory {
  id: number;
  name: string;
  /**
   * URL-friendly version (e.g., emergency-services)
   */
  slug: string;
  description?: string | null;
  icon?: ('zap' | 'code' | 'wrench' | 'building' | 'globe' | 'shield') | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-tags".
 */
export interface ArticleTag {
  id: number;
  name: string;
  /**
   * URL-friendly version (e.g., ai-seo)
   */
  slug: string;
  description?: string | null;
  color?: ('orange' | 'blue' | 'green' | 'purple' | 'pink' | 'gray') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL path (e.g., emergency-website-repair-guide)
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Publication date (used for sorting and display)
   */
  publishedAt?: string | null;
  category: number | ArticleCategory;
  /**
   * Tags for filtering and categorization
   */
  tags?: (number | ArticleTag)[] | null;
  featuredImage?: (number | null) | Media;
  /**
   * The style used for the AI-generated featured image
   */
  imageStyle?: ('illustration' | 'photorealistic-people' | 'photorealistic-abstract' | 'tech-minimal') | null;
  /**
   * AI-generated infographic for the article
   */
  infographic?: (number | null) | Media;
  /**
   * Short summary for article cards and SEO (max 160 chars)
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    /**
     * SEO title (defaults to article title if empty). Max 60 chars.
     */
    metaTitle?: string | null;
    /**
     * SEO meta description. Max 160 chars.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for this article
     */
    keywords?: string | null;
    /**
     * Canonical URL if different from default
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph image (defaults to featured image)
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
  };
  /**
   * For JSON-LD schema markup
   */
  structuredData?: {
    articleType?: ('Article' | 'BlogPosting' | 'NewsArticle' | 'HowTo') | null;
    author?: string | null;
  };
  /**
   * Feature this article prominently
   */
  featured?: boolean | null;
  /**
   * Display order for featured articles
   */
  order?: number | null;
  /**
   * Tracks the cost of AI-generated content for this article
   */
  generationCosts?: {
    topicResearch?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      /**
       * Cost in USD
       */
      cost?: number | null;
    };
    topicParsing?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      /**
       * Cost in USD
       */
      cost?: number | null;
    };
    outlineGeneration?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      /**
       * Cost in USD
       */
      cost?: number | null;
    };
    sectionGeneration?:
      | {
          section?: string | null;
          inputTokens?: number | null;
          outputTokens?: number | null;
          /**
           * Cost in USD
           */
          cost?: number | null;
          id?: string | null;
        }[]
      | null;
    composition?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      /**
       * Cost in USD
       */
      cost?: number | null;
    };
    articleGeneration?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      /**
       * Cost in USD
       */
      cost?: number | null;
    };
    infographicData?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      /**
       * Cost in USD
       */
      cost?: number | null;
    };
    featuredImage?: {
      model?: string | null;
      /**
       * GPU seconds
       */
      predictTime?: number | null;
      /**
       * Cost in USD
       */
      cost?: number | null;
    };
    infographicImage?: {
      model?: string | null;
      /**
       * GPU seconds
       */
      predictTime?: number | null;
      /**
       * Cost in USD
       */
      cost?: number | null;
    };
    inlineImages?:
      | {
          context?: string | null;
          model?: string | null;
          /**
           * GPU seconds
           */
          predictTime?: number | null;
          /**
           * Cost in USD
           */
          cost?: number | null;
          id?: string | null;
        }[]
      | null;
    additionalInfographics?:
      | {
          headline?: string | null;
          model?: string | null;
          /**
           * GPU seconds
           */
          predictTime?: number | null;
          /**
           * Cost in USD
           */
          cost?: number | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Total generation cost in USD
     */
    totalCost?: number | null;
    /**
     * When this article was generated
     */
    generatedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks in-progress article generations for recovery
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-generation-checkpoints".
 */
export interface ArticleGenerationCheckpoint {
  id: number;
  generationId: string;
  stage?: ('topic' | 'content' | 'infographic' | 'images' | 'upload' | 'create') | null;
  status?: ('in_progress' | 'failed' | 'completed') | null;
  topic?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  article?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The ID of the draft article created from this generation
   */
  articleId?: (number | null) | Article;
  infographicData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  imageResults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  uploadedMedia?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  costs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorMessage?: string | null;
  startedAt: string;
  lastUpdatedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-landing-pages".
 */
export interface IndustryLandingPage {
  id: number;
  industryName: string;
  /**
   * URL path (e.g., dental, real-estate)
   */
  slug: string;
  hero: {
    headline: string;
    tagline: string;
    description: string;
  };
  painPoints?:
    | {
        title: string;
        description: string;
        /**
         * Lucide icon name
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        serviceTitle: string;
        industrySpecificBenefit: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        stepNumber: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  statistics?:
    | {
        value: string;
        label: string;
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    title: string;
    description: string;
  };
  featuredImage?: (number | null) | Media;
  /**
   * AI-generated infographic for this industry
   */
  infographic?: (number | null) | Media;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
  };
  generationCosts?: {
    industryResearch?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      cost?: number | null;
    };
    contentGeneration?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      cost?: number | null;
    };
    featuredImage?: {
      model?: string | null;
      predictTime?: number | null;
      cost?: number | null;
    };
    infographicData?: {
      inputTokens?: number | null;
      outputTokens?: number | null;
      cost?: number | null;
    };
    infographicImage?: {
      model?: string | null;
      predictTime?: number | null;
      cost?: number | null;
    };
    totalCost?: number | null;
    generatedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks in-progress industry page generations for recovery
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-generation-checkpoints".
 */
export interface IndustryGenerationCheckpoint {
  id: number;
  generationId: string;
  industryName: string;
  stage?: ('context' | 'content' | 'infographic' | 'images' | 'upload' | 'create') | null;
  status?: ('in_progress' | 'failed' | 'completed') | null;
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pageData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  infographicData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  imageResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  uploadedMedia?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  costs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorMessage?: string | null;
  startedAt: string;
  lastUpdatedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'projects';
        value: number | Project;
      }
    | {
        relationTo: 'industry-landing-pages';
        value: number | IndustryLandingPage;
      };
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'article-categories';
        value: number | ArticleCategory;
      } | null)
    | ({
        relationTo: 'article-tags';
        value: number | ArticleTag;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'article-generation-checkpoints';
        value: number | ArticleGenerationCheckpoint;
      } | null)
    | ({
        relationTo: 'industry-landing-pages';
        value: number | IndustryLandingPage;
      } | null)
    | ({
        relationTo: 'industry-generation-checkpoints';
        value: number | IndustryGenerationCheckpoint;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  filterCategory?: T;
  image?: T;
  imagePath?: T;
  link?: T;
  summary?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  client?: T;
  year?: T;
  challenge?: T;
  solution?: T;
  results?:
    | T
    | {
        metric?: T;
        value?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories_select".
 */
export interface ArticleCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-tags_select".
 */
export interface ArticleTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  category?: T;
  tags?: T;
  featuredImage?: T;
  imageStyle?: T;
  infographic?: T;
  excerpt?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  structuredData?:
    | T
    | {
        articleType?: T;
        author?: T;
      };
  featured?: T;
  order?: T;
  generationCosts?:
    | T
    | {
        topicResearch?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        topicParsing?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        outlineGeneration?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        sectionGeneration?:
          | T
          | {
              section?: T;
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
              id?: T;
            };
        composition?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        articleGeneration?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        infographicData?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        featuredImage?:
          | T
          | {
              model?: T;
              predictTime?: T;
              cost?: T;
            };
        infographicImage?:
          | T
          | {
              model?: T;
              predictTime?: T;
              cost?: T;
            };
        inlineImages?:
          | T
          | {
              context?: T;
              model?: T;
              predictTime?: T;
              cost?: T;
              id?: T;
            };
        additionalInfographics?:
          | T
          | {
              headline?: T;
              model?: T;
              predictTime?: T;
              cost?: T;
              id?: T;
            };
        totalCost?: T;
        generatedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-generation-checkpoints_select".
 */
export interface ArticleGenerationCheckpointsSelect<T extends boolean = true> {
  generationId?: T;
  stage?: T;
  status?: T;
  topic?: T;
  article?: T;
  articleId?: T;
  infographicData?: T;
  imageResults?: T;
  uploadedMedia?: T;
  costs?: T;
  options?: T;
  errorMessage?: T;
  startedAt?: T;
  lastUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-landing-pages_select".
 */
export interface IndustryLandingPagesSelect<T extends boolean = true> {
  industryName?: T;
  slug?: T;
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        description?: T;
      };
  painPoints?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  services?:
    | T
    | {
        serviceTitle?: T;
        industrySpecificBenefit?: T;
        id?: T;
      };
  process?:
    | T
    | {
        stepNumber?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  statistics?:
    | T
    | {
        value?: T;
        label?: T;
        source?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  featuredImage?: T;
  infographic?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  generationCosts?:
    | T
    | {
        industryResearch?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        contentGeneration?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        featuredImage?:
          | T
          | {
              model?: T;
              predictTime?: T;
              cost?: T;
            };
        infographicData?:
          | T
          | {
              inputTokens?: T;
              outputTokens?: T;
              cost?: T;
            };
        infographicImage?:
          | T
          | {
              model?: T;
              predictTime?: T;
              cost?: T;
            };
        totalCost?: T;
        generatedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-generation-checkpoints_select".
 */
export interface IndustryGenerationCheckpointsSelect<T extends boolean = true> {
  generationId?: T;
  industryName?: T;
  stage?: T;
  status?: T;
  context?: T;
  pageData?: T;
  infographicData?: T;
  imageResult?: T;
  uploadedMedia?: T;
  costs?: T;
  options?: T;
  errorMessage?: T;
  startedAt?: T;
  lastUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-generation-settings".
 */
export interface ContentGenerationSetting {
  id: number;
  topicResearch?: {
    /**
     * Use {{keywordList}} as a placeholder for the keyword list.
     */
    prompt?: string | null;
  };
  articleGeneration?: {
    /**
     * Use {{title}}, {{angle}}, {{targetKeyword}}, and {{location}} as placeholders.
     */
    prompt?: string | null;
  };
  featuredImageStyles?:
    | {
        name: string;
        model: string;
        /**
         * Use {{title}}, {{excerpt}}, and {{keywords}} as placeholders.
         */
        prompt: string;
        id?: string | null;
      }[]
    | null;
  infographic?: {
    dataExtractionPrompt?: string | null;
    /**
     * Use {{headline}}, {{problemStatement}}, {{statsSection}}, {{stepsSection}}, {{tipsSection}}, and {{callToAction}} as placeholders.
     */
    imageGenerationPrompt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-generation-settings_select".
 */
export interface ContentGenerationSettingsSelect<T extends boolean = true> {
  topicResearch?:
    | T
    | {
        prompt?: T;
      };
  articleGeneration?:
    | T
    | {
        prompt?: T;
      };
  featuredImageStyles?:
    | T
    | {
        name?: T;
        model?: T;
        prompt?: T;
        id?: T;
      };
  infographic?:
    | T
    | {
        dataExtractionPrompt?: T;
        imageGenerationPrompt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}